### ISSUE TITLE
Revert with Error Message & Custom Errors

### ISSUE THREAD

**Issue by alymurtazamemon** [Cyfrin/foundry-fund-me-f23#1]
@PatrickAlphaC We can add the error message and custom errors in these tests as we did in the Hardhat tests;
```solidity
function testFundFailsWithoutEnoughETH() public {
    vm.expectRevert(bytes("You need to spend more ETH!"));
    fundMe.fund();
}
```

```solidity
function testOnlyOwnerCanWithdraw() public funded {
    vm.expectRevert(FundMe__NotOwner.selector);
    fundMe.withdraw();
}
```

**Comment by PatrickAlphaC** [comment]
yes! 

I will be teaching this, but in the lesson after this :)

**Comment by trangnv** [comment]
Without message, the test would fail
```solidity
function testFailWithNotEnoughEth() public {
        vm.expectRevert(); // next line should revert
        fundMe.fund();
    } 
```
I guess because of Foundry version? I'm having `forge 0.2.0`

**Comment by PatrickAlphaC** [comment]
@trangnv what are you asking? Yes, it should revert. If it's not, you might be accidentally funding it?

**Comment by trangnv** [comment]
- The test fails if I use `vm.expectRevert();` without any error message
- I had to put `vm.expectRevert(bytes("More ETH"));` then it worked

I'm not sure if it's a Foundry bug or I missed something.
