### ISSUE TITLE
`forge test` installs release 0.0.10 of foundry-devops

### ISSUE THREAD

**Issue by ShayanShamsi** [Cyfrin/foundry-fund-me-f23#13]
Hello!

**Steps to recreate**

1. Clone the repo
2. Run forge test and wait for the dependencies to install
3. Get the following error:
`[⠊] Compiling...
Error: 
File cannot be resolved due to mismatch of file name case: "/home/shayan/Documents/Foundry-2023/original-foundry-fund-me-f23/lib/forge-std/src/Console.sol": No such file or directory (os error 2).
 Found existing file: "/home/shayan/Documents/Foundry-2023/original-foundry-fund-me-f23/lib/forge-std/src/console.sol"
 Please check the case of the import..
    --> "/home/shayan/Documents/Foundry-2023/original-foundry-fund-me-f23/lib/foundry-devops/src/DevOpsTools.sol"
        "forge-std/Console.sol"`

This indicates that `forge test` is installing the 0.0.10 release of foundry-devops and not the latest release. The issue causing the error was fixed [in the latest release](https://github.com/Cyfrin/foundry-devops/compare/0.0.10...0.0.11) more than two months ago. Running `forge install Cyfrin/foundry-devops` fixes the error since that installs the 0.0.11 release.

I have no idea if this is being caused by an issue in this repository or if there is a problem with Foundry's forge tool. If the latter is true, I will close this issue and open one in the foundry repository. I hope someone can clarify this for me.

**Comment by PatrickAlphaC** [comment]
Thank you for this!

Yep... Turns out I had the wrong commit hash in the submodules!

It should be fixed now

https://github.com/Cyfrin/foundry-fund-me-f23/commit/68f7d4d88fc698c6a01f1b64d37e65f93ca0eff4
