### ISSUE TITLE
Typo in readme.md file

### ISSUE THREAD

**Issue by Anupreet1213** [Cyfrin/foundry-fund-me-f23#15]
I have been going through readme file and saw a typo, here it is:

## Screenshot
<img width="872" alt="idk" src="https://github.com/Cyfrin/foundry-fund-me-f23/assets/93524594/6ae94bd1-e3d6-485f-8a49-beec7e39f11b">

There should be sepolia testnet, not goerli testnet.
Should I make a pr @PatrickAlphaC?

**Comment by Ritik-Agarwal50** [comment]
Go for it sir
