### ISSUE TITLE
[Tips] Foundry match test command updated.

### ISSUE THREAD

**Issue by psyljz** [Cyfrin/foundry-fund-me-f23#28]
Summary:
`Error: Unexpected argument '-m' found when running 'forge test' command.`

Context:
I encountered this error while following a video tutorial on testing functions using the Forge command. The tutorial demonstrated running a single function test with the command "forge test -m testMinimumDollarIsFive". I am using the latest version of Forge and my development environment is set up according to the tutorial instructions.

Command Used:

`forge test -m testMinimumDollarIsFive`

Error Message:

`error: unexpected argument '-m' found`

Suggested Solution:

Using the command `forge test --match-test testMinimumDollarIsFive` instead.

Additional Information:
I found more information about Forge test commands in the official documentation: [Forge Test Commands Documentation](https://book.getfoundry.sh/reference/forge/forge-test)

**Comment by sahbaazansari** [comment]
Yup, that's the correct way of using the command. I also had the same issue but trying the command below gave me the correct idea. 
```
forge test --help
```

**Comment by ElahiAli** [comment]
You can also run specific tests by passing a filter:
```forge test --match-contract ComplicatedContractTest --match-test testDeposit```

**Comment by PatrickAlphaC** [comment]
Yep! Use `--mt` now!
