### ISSUE TITLE
Makefile not working with WSL

### ISSUE THREAD

**Issue by YoexRep** [Cyfrin/foundry-fund-me-f23#34]
Hi, when I try to run the **make** command I get this error:

```
Command 'make' not found, but can be installed with:

sudo apt install make        # version 4.2.1-1.2, or
sudo apt install make-guile  # version 4.2.1-1.2
```

 
if i try to install it with:

`sudo apt install make`

It gives me a dependencies error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 github-desktop : Depends: libgtk-3-0 but it is not going to be installed
                  Depends: libnotify4 but it is not going to be installed
                  Depends: libnss3 but it is not going to be installed
                  Depends: xdg-utils but it is not going to be installed
                  Depends: libatspi2.0-0 but it is not going to be installed
                  Depends: libgbm1 but it is not going to be installed
                  Depends: libsecret-1-0 but it is not going to be installed
                  Depends: gnome-keyring but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

I think it's because I'm using WSL, was someone able to install it?

**Comment by andrejscek** [comment]
Were you able to make it work?

I did not have any issue running the make command after installing make with WSL :
`sudo apt install make`

Just need to make sure you have the Makefile named as "Makefile" (first time I missnamed it as MakeFile and the make command did not know where to look)  and have it in the root of the directory.

**Comment by YoexRep** [comment]
yes, i was able to get it working, apparently i needed to update the wsl, these were the commands i used:

`sudo apt update`

and

`sudo apt --fix broken install`

**Comment by PatrickAlphaC** [comment]
Nice! Thank you!
