### ISSUE TITLE
hoax not working inside for loop

### ISSUE THREAD

**Issue by StefaniaPozzi** [Cyfrin/foundry-fund-me-f23#39]
Hi! Running some tests **test_successWithdrawMultipleFunders** as described [here](https://youtu.be/sas02qSFZ74?t=5227).
The test runs fine with `startPrank` and `stopPrank` inside the for loop, but I get an error while using `hoax` (if the loop array makes more than 1 loop).

```[FAIL. Reason: You cannot overwrite `prank` until it is applied at least once]```

This works fine:
```
   for (uint160 i = 1; i < 10; i++) {
            vm.startPrank(address(i));
            vm.deal(address(i), AMOUNT_TO_BE_SENT);
            fundMe.fund{value: AMOUNT_TO_BE_SENT};
            vm.stopPrank();
        }
```

But this does not:
```
   for (uint160 i = 1; i < 10; i++) {
            hoax(address(i), AMOUNT_TO_BE_SENT);
            fundMe.fund{value: AMOUNT_TO_BE_SENT};
        }
```

Any idea why this happens? 
Thanks!! 
S 🔥

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions
