### ISSUE TITLE
import AggregatorV3Interface.sol. 

### ISSUE THREAD

**Issue by GTK-ARJUN** [Cyfrin/foundry-fund-me-f23#46]
I have followed the process till 
https://youtu.be/sas02qSFZ74?si=9yp_UIz3cD0y51Ip&t=660

however, I am getting an error as below:
Error (6275): Source "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol" not found: File not found. Searched the following locations: "/home/founder/foundry-f23/foundry-fund-me-f23".
 --> src/FundMe.sol:6:1:
  |
6 | import {AggregatorV3Interface} from "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Do I have to manually create a file of AggregatorV3Interface.sol?

**Comment by SolidLearner** [comment]
Check your foundry.toml file
Do you have the remappings written correctly?
```toml
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
```

**Comment by Depauli1** [comment]
I think that would work

**Comment by PatrickAlphaC** [comment]
@thomasender you'd have to make a pull request to this repo, not push directly!

**Comment by thomasender** [comment]
> @thomasender you'd have to make a pull request to this repo, not push directly!

@PatrickAlphaC PR created
