### ISSUE TITLE
Question about FundFundme

### ISSUE THREAD

**Issue by zhang-shizhe** [Cyfrin/foundry-fund-me-f23#47]
I am a little comfused about the FundFundMe part,
```
FundMe(payable(mostRecentlyDeployed)).fund{value: SEND_VALUE}();
```
What does the parameter we pass in *mostRecentlyDeployed* represent? I guess it is the address of the FundMe contract. However, in the file FundMe.sol, 
```
    constructor(address priceFeed) {
        i_owner = msg.sender;
        s_priceFeed = AggregatorV3Interface(priceFeed);
    }
```
the parameter is the address of the priceFeed.

**Comment by PatrickAlphaC** [comment]
Great question!

So the constructor is only called when we _deploy_ the contract. 

In this:
```solidity
FundMe(payable(mostRecentlyDeployed)).fund{value: SEND_VALUE}();
```

We are saying "The payable `FundMe` contract at address `mostRecentlyDeployed`, you should call the `fund` function and send `SEND_VALUE` amount of `value`".

Does that make sense? 

Also, for these questions, 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464
