### ISSUE TITLE
foundry-fund-me-f23/script /HelperConfig.s.sol

### ISSUE THREAD

**Issue by GhislainTselone** [Cyfrin/foundry-fund-me-f23#49]
Issue : 
```solidity
if (activeNetworkConfig.priceFeed != address(0)) {
            return activeNetworkConfig;
        }
```

Source (from  the HelperConfig.s contract) : 
``` solidity 
 function getOrCreateAnvilEthConfig() public returns (NetworkConfig memory anvilNetworkConfig) {
        // Check to see if we set an active network config
        if (activeNetworkConfig.priceFeed != address(0)) {
            return activeNetworkConfig;
        }
        vm.startBroadcast();
        MockV3Aggregator mockPriceFeed = new MockV3Aggregator(
            DECIMALS,
            INITIAL_PRICE
        );
        vm.stopBroadcast();
        emit HelperConfig__CreatedMockPriceFeed(address(mockPriceFeed));

        anvilNetworkConfig = NetworkConfig({priceFeed: address(mockPriceFeed)});
```

Question: How is that piece of code not redundant ? As the HelperConfig and the Mock itself are always redeployed in the setup during testing phase on the ANVIL local network, and there's no situation where the activeNetworkConfig.priceFeed would be set to a non-zero address before deploying the contract.

**Comment by PatrickAlphaC** [comment]
> always redeployed in the setup during testing phase on the ANVIL local network

You could have a script that doesn't deploy the mocks right away.
