### ISSUE TITLE
File Name Case Mismatch in DevOpsTools.sol prevents successful compilation

### ISSUE THREAD

**Issue by BlockChomper** [Cyfrin/foundry-fund-me-f23#5]
## Issue with Solidity import in `DevOpsTools.sol`

In the `DevOpsTools.sol` file located under the `lib/foundry-devops/src/` directory, there is an issue with a specific import statement:

```solidity
import {console} from "forge-std/Console.sol";
```

In order to resolve this issue, the file reference should match the actual file name including the case of the letters. So, if the actual file is named console.sol, the correct import statement would be:

```solidity
import {console} from "forge-std/console.sol";
```

This change should resolve the compilation issue.

**Comment by PatrickAlphaC** [comment]
Thanks! I think this is fixed?

**Comment by BlockChomper** [comment]
Awesome! Thanks for the great content Patrick, glad to contribute in some small way :)
