### ISSUE TITLE
VM command from Script contract

### ISSUE THREAD

**Issue by GhislainTselone** [Cyfrin/foundry-fund-me-f23#51]
Observation: I noticed that there are some contract that have been deployed between : 

```solidity 
vm.startBroadcast()
...... 
vm.stopBroadcast()
```

Questions: 
1. Why some need it and why others don't ?
2. If i try to deploy a contract  without it, it won't work ?

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions
