### ISSUE TITLE
Testing of funding fundMe function is reverting an error.

### ISSUE THREAD

**Issue by Rhythm23-tech** [Cyfrin/foundry-fund-me-f23#58]
function testFundUpdatesFundedDataStructure() public {
        vm.prank(USER);
        fundMe.fund{value: SEND_VALUE}();
        uint256 amountFunded = fundMe.getAddresstoAmountFunded(USER);
        console.log(amountFunded);
        console.log(SEND_VALUE);
        assertEq(amountFunded, SEND_VALUE);
    }

Found invalid setup function "setup()" did you mean "setUp()"?
Running 1 test for test/unit/FundMeTest.t.sol:FundMeTest
[FAIL. Reason: EvmError: Revert] testFundUpdatesFundedDataStructure() (gas: 10098)
Traces:
  [10098] FundMeTest::testFundUpdatesFundedDataStructure()
    ├─ [0] VM::prank(user: [0x6a9aBf7c6aD2E88df83D5F9a76b30e3Bb60adF1D])
    │   └─ ← ()
    └─ ← EvmError: Revert

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 836.60µs
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/unit/FundMeTest.t.sol:FundMeTest
[FAIL. Reason: EvmError: Revert] testFundUpdatesFundedDataStructure() (gas: 10098)

Encountered a total of 1 failing tests, 0 tests succeeded

The above-given function is a test function used to test and update fundMe function but after verifying all the contracts several times still the test function shows the same error. I think that the fundMe contract is unable to fetch the pricefeed address declared in HelperConfig.s.sol. FundMe contract is the same as that taught by Patrik. If someone knows how to resolve it or might have come across such an error. Your help will be appreciated.

Thank you in advance.

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464
