### ISSUE TITLE
Problem With the lesson 7

### ISSUE THREAD

**Issue by ElMaestruli28** [Cyfrin/foundry-fund-me-f23#64]
When i saw the lesson 7, i had a problem with the FundMeTest because the code of FundMe was changed to the one in the video. Then I have few problems with the test, one of the errors

`[FAIL. Reason: EvmError: Revert] testPriceFeedVersionIsAccurate() (gas: 7836)
Suite result: FAILED. 2 passed; 1 failed; 0 skipped; finished in 8.27ms (5.84ms CPU time)

Ran 1 test suite in 18.13ms (8.27ms CPU time): 2 tests passed, 1 failed, 0 skipped (3 total tests)

Failing tests:
Encountered 1 failing test in test/FundMeTest.s.sol:FundMeTest
[FAIL. Reason: EvmError: Revert] testPriceFeedVersionIsAccurate() (gas: 7836)

Encountered a total of 1 failing tests, 2 tests succeeded`

greetings from argentina

**Comment by codexNature** [comment]
Hi, I wish you had provided the function, however below is how I wrote my test function for "testPriceFeedVersionIsAccurate()" and it passed the test just fine, try it.
I hope it helps.

`function testPriceFeedVersionIsAccurate() public {
        uint256 version = fundMe.getVersion();
        assertEq(version, 4);
    }`

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discussion on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464

**Comment by ElMaestruli28** [comment]
> Hi, I wish you had provided the function, however below is how I wrote my test function for "testPriceFeedVersionIsAccurate()" and it passed the test just fine, try it. I hope it helps.
> 
> `function testPriceFeedVersionIsAccurate() public { uint256 version = fundMe.getVersion(); assertEq(version, 4); }`

Hello bro, I wrote the same line and i have the same problem, I pass you the line, ``function testPriceFeedVersionIsAccurate() public view{
        uint256 version = fundMe.getVersion(); assertEq(version, 4); }``

But the error is the same, error: ``[FAIL. Reason: EvmError: Revert] testPriceFeedVersionIsAccurate() (gas: 7836)
Traces:
  [7836] FundMeTest::testPriceFeedVersionIsAccurate()
    ├─ [2729] FundMe::getVersion() [staticcall]
    │   ├─ [214] FundMeTest::version() [staticcall]
    │   │   └─ ← EvmError: Revert
    │   └─ ← EvmError: Revert
    └─ ← EvmError: Revert

Suite result: FAILED. 2 passed; 1 failed; 0 skipped; finished in 3.06s (1.64ms CPU time)

Ran 1 test suite in 4.12s (3.06s CPU time): 2 tests passed, 1 failed, 0 skipped (3 total tests)

Failing tests:
Encountered 1 failing test in test/FundMeTest.s.sol:FundMeTest
[FAIL. Reason: EvmError: Revert] testPriceFeedVersionIsAccurate() (gas: 7836)

Encountered a total of 1 failing tests, 2 tests succeeded``
