### ISSUE TITLE
I can't import DeployFundMe.s.Sol

### ISSUE THREAD

**Issue by Crocosaurus96** [Cyfrin/foundry-fund-me-f23#66]
Hello!

I am receiving this error while compiling:

` ` `
Error (6275): Source "script/DeployFundMe.s.sol" not found: File not found. Searched the following locations: "/home/useradd/foundry-f23/foundry-fund-me-f23".
ParserError: Source "script/DeployFundMe.s.sol" not found: File not found. Searched the following locations: "/home/useradd/foundry-f23/foundry-fund-me-f23".
 --> test/FundMeTest.t.sol:7:1:
  |
7 | import {DeployFundMe} from "../../script/DeployFundMe.s.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

` ` `

Here is my code and my Foundry-Fund-Me-F23 folder:

![image](https://github.com/Cyfrin/foundry-fund-me-f23/assets/106905410/12fa4aea-4b3f-4faa-8d90-1f3aab436e62)

I can't figure it out why it doesn't work, and other imports work.

**Comment by khayss** [comment]
The import path is wrong. From your folder structure, you only need to go up one level
```
"..//script/DeployFundMe.s.sol"
```

That should fix your code.

**Comment by PatrickAlphaC** [comment]
Glad you solved it!
