### ISSUE TITLE
Clarification Needed: Actual Funder in testUserCanFundAndOwnerWithdraw Test

### ISSUE THREAD

**Issue by JarvisChan666** [Cyfrin/foundry-fund-me-f23#69]
## Description:

Upon reviewing the **testUserCanFundAndOwnerWithdraw** test within the **InteractionsTest** , I've encountered a discrepancy regarding the identity of the **actual funder** in the scenario. The test name suggests that **a user (referred to as USER) funds the FundMe contract.** However, through logging and analysis, it appears that **the actual funder is the default account set in Foundry's lib\\forge-std\\src\\Base.sol**, specifically the address **0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38**.

![default sender in foundry](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/b097be91-c13f-42f1-acf9-be69f32c6ec9/ee86e85b-580b-45b4-8534-1bf54a90060d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My9iMDk3YmU5MS1jMTNmLTQyZjEtYWNmOS1iZTY5ZjMyYzZlYzkvZWU4NmU4NWItNTgwYi00NWI0LTg1MzQtMWJmNTRhOTAwNjBkIiwiaWF0IjoxNzE0NzU0NzA2LCJleHAiOjMzMjg1MzE0NzA2fQ.ZH5rtkvJWdkwkCsKDsjj7ZC8jnUboZBWm01Ryji49uY "=1130x")

## Observed Behavior:

Logs and analysis indicate that the **fundFundMe** function within the interaction scripts results in **funding from the default Foundry account** (0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38), rather than **the USER constant (address(1))** as might be inferred from the test's name.

## Expected Behavior:

The expectation, based on the test's naming convention, is for **USER to be the entity funding the FundMe contract**. This discrepancy could lead to confusion regarding the roles and actions being tested, particularly in terms of accurately simulating user interactions within this project.

## Proposed Solutions:

1. **Explicitly Simulate USER as the Funder:**
   Modify the test to explicitly **use vm.prank(USER)** before calling the fund function on the FundMe contract. This change would **ensure that USER is accurately represented as the funder** in the test scenario:

InteractionsTest.t.sol

```solidity
function testUserCanFundAndOwnerWithdraw() public {
    // Setup code...
 
    // Explicitly simulate USER as the funder
    vm.prank(USER);
    fundMe.fund{value: SEND_VALUE}();
    // FundFundMe fundFundMe = new FundFundMe();
    // fundFundMe.fundFundMe(address(fundMe));
 
 
    // Withdrawal simulation and assertions...
}
```

1. **Clarify the Role of the Default Foundry Account:** 
   If the intention is indeed for the default Foundry account to fund the contract in this test scenario, it may be beneficial to clarify this within the **test comments** or documentation to prevent any misunderstandings regarding the roles and actions being tested.

The complete test code:

```solidity
 function testUserCanFundAndOwnerWithdraw() public {
        console.log("-------BEFORE FUNDING-------");
        uint256 preFundUserBalance = address(USER).balance;
        uint256 preFundOwnerBalance = address(fundMe.getOwner()).balance;
        uint256 preFundFundMeBalance = address(fundMe).balance;
        console.log("preUserBalance: %s", preFundUserBalance);
        console.log("preOwnerBalance: %s", preFundOwnerBalance);
        console.log("preFundFundMeBalance: %s", preFundFundMeBalance);


        console.log("-------START FUNDING-------");
        vm.prank(USER);
        fundMe.fund{value: SEND_VALUE}();
        // FundContract fundFundMe = new FundContract();
        // fundFundMe.fundFundMe(address(fundMe));

        uint256 afterFundUserBalance = address(USER).balance;
        uint256 afterFundOwnerBalance = address(fundMe.getOwner()).balance;
        uint256 afterFundFundMeBalance = address(fundMe).balance;
        console.log("afterFundUserBalance: %s", afterFundUserBalance);
        console.log("afterFundOwnerBalance: %s", afterFundOwnerBalance);
        console.log("afterFundFundMeBalance: %s", afterFundFundMeBalance);
        assertEq(afterFundUserBalance + SEND_VALUE, preFundUserBalance);
        assertEq(afterFundFundMeBalance, preFundFundMeBalance + SEND_VALUE);


        console.log("-------START WITHDRAWING-------");
        WithdrawFundMe withdrawFundMe = new WithdrawFundMe();
        withdrawFundMe.withdrawFundMe(address(fundMe));

        uint256 afterWithdrawUserBalance = address(USER).balance;
        uint256 afterWithdrawOwnerBalance = address(fundMe.getOwner()).balance;
        uint256 afterWithdrawFundMeBalance = address(fundMe).balance;
        console.log("afterWithdrawUserBalance: %s", afterWithdrawUserBalance);
        console.log("afterWithdrawOwnerBalance: %s", afterWithdrawOwnerBalance);
        console.log("afterWithdrawFundMeBalance: %s", afterWithdrawFundMeBalance);
        assert(afterWithdrawFundMeBalance == 0);
        assertEq(afterWithdrawOwnerBalance, preFundOwnerBalance + afterFundFundMeBalance);
        console.log("-------SHOW FUNDER-------");
        console.log("The actual Funder is the default address set by foundry:", address(msg.sender));
        console.log("The funder we think:", address(USER));
    }
```

**Test log before fixing**(Funder is default address set by Foundry), and USER balance won't change, it didn't do anything:

![user wont fund](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/55cb613f-6b52-4618-9bfb-fbc6b228540e/f2743907-0ed9-445a-a5e1-1dfa382a8ae3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My81NWNiNjEzZi02YjUyLTQ2MTgtOWJmYi1mYmM2YjIyODU0MGUvZjI3NDM5MDctMGVkOS00NDVhLWE1ZTEtMWRmYTM4MmE4YWUzIiwiaWF0IjoxNzE0NzU0NzA2LCJleHAiOjMzMjg1MzE0NzA2fQ.X6GMZYyHO0brzAVnTQmCOUD_R9D1tX1W-EUdGwtiRqQ "=698x")

**Test log after fixing**(Using Prank and comment out using FundFundMe to fund), making the USER is the actual funder we want:

![user actually fund](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/7d178c98-c015-43ef-8d40-78469cc1df19/5deee802-a3c5-482e-8337-660fd1d9b2ee?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My83ZDE3OGM5OC1jMDE1LTQzZWYtOGQ0MC03ODQ2OWNjMWRmMTkvNWRlZWU4MDItYTNjNS00ODJlLTgzMzctNjYwZmQxZDliMmVlIiwiaWF0IjoxNzE0NzU0NzA2LCJleHAiOjMzMjg1MzE0NzA2fQ.rHihka62ZDQN8WVoG_GJ20pdnuuWgBPw9aqZESNhEg4 "=629x")

**Comment by JarvisChan666** [comment]
If I am correct, can I PR for it? 
Solution 1: Using **USER** to fund and don't use **FundFundMe** to fund. 
Solution 2: just **change the test name**(still using the default address from foundry). 
Or other solution?

**Comment by JarvisChan666** [comment]
Can I submit a PR for it if it's right? Using USER to make it more readable instead of using FundFundMe to fund
Solution 1: Using USER to fund and don't use FundFundMe to fund.
Solution 2:  change the test name(still using the default address from foundry).
Or other solution?

**Comment by PatrickAlphaC** [comment]
Love this.

When teaching... I sort of do some "white lies" to make digest the information easier, this is one of them. I'd love to have a PR to do this, so long as you add a comment saying why we are doing this :)
