### ISSUE TITLE
Unable to verify contract on Sepolia

### ISSUE THREAD

**Issue by DS-Coding0** [Cyfrin/foundry-fund-me-f23#73]
```
Details: `Fail - Unable to verify. Compiled contract deployment bytecode does NOT match the transaction deployment bytecode.`
```

I get this error if i want to verify my contract.

I tried verify manually with this command:

```
forge verify-contract --rpc-url $SEPOLIA_RPC_URL --etherscan-api-key $ETHERSCAN_API_KEY --watch 0xD41F409fAA7204EA6C03dAaa145233D501E3B121 script/DeployFundMe.s.sol:DeployFundMe --compiler-version 0.8.18
```

First i had deploy the contract with this command:

```
make deploy-sepolia
```

which include:

```
forge script script/DeployFundMe.s.sol:DeployFundMe --rpc-url $(SEPOLIA_RPC_URL) --account MetaMaskSep --broadcast --verify --etherscan-api-key $(ETHERSCAN_API_KEY) -vvvv
```

At deploying i get this error:

```
Error: 
Etherscan could not detect the deployment.
make: *** [Makefile:6: deploy-sepolia] Error 1
```

**Comment by PatrickAlphaC** [comment]
So, did you deploy the contract then?

**Comment by DS-Coding0** [comment]
Yes the contract deployed with no problems.

I've uploaded the complete code in my repo.

Deploying is no problem, only verify doesn't work.

**Comment by PatrickAlphaC** [comment]
Hmm... Do you have the contract address? 

> Etherscan could not detect the deployment.

This says Etherscan couldn't find the address. You could try the `forge-verify` command?

**Comment by DS-Coding0** [comment]
> Hmm... Do you have the contract address? 
> 
> > Etherscan could not detect the deployment.
> 
> This says Etherscan couldn't find the address. You could try the `forge-verify` command? 

That's because listening on etherscan took more time than the deployment give.. but deploying is successful.

I tried manually with forge verify-contract but this ends in an error that the contract doesn't have the same byte code.

I would try again next week and would give you the contract address if this would help.

**Comment by PatrickAlphaC** [comment]
Ah. You'd need to recompile with the same exact compilation settings. 

Or... Etherscan could just be being mean. You might have to manually verify via their UI and the `standard-json` method. Run the forge verify method with `--show-standard-json-input` and then take that file directly to etherscan and try to verify via the UI.

This is a pretty big downside of relying on a centralized party for this :/

**Comment by cromewar** [comment]
@DS-Coding0  can you confirm @PatrickAlphaC solved your issue?

**Comment by DS-Coding0** [comment]
Hey, verify has worked now correctly thanks for your help.

I think the Sepolia Net had problems at this time.
