### ISSUE TITLE
chainlink Brownie Contracts

### ISSUE THREAD

**Issue by llakterian** [Cyfrin/foundry-fund-me-f23#77]
I have tried to forge install the chainlink brownie contracts but keep getting this error; 
'''
forge install smartcontractkit/chainlink-brownie-contracts --no-commit
Installing chainlink-brownie-contracts in /home/rumpas/foundry-f23/foundry-fund-me-f23/lib/chainlink-brownie-contracts (url: Some("https://github.com/smartcontractkit/chainlink-brownie-contracts"), tag: None)
Cloning into '/home/rumpas/foundry-f23/foundry-fund-me-f23/lib/chainlink-brownie-contracts'...
remote: Enumerating objects: 34035, done.
remote: Counting objects: 100% (3636/3636), done.
remote: Compressing objects: 100% (1550/1550), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 6181 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/smartcontractkit/chainlink-brownie-contracts' into submodule path '/home/rumpas/foundry-f23/foundry-fund-me-f23/lib/chainlink-brownie-contracts' failed
Error: 
git submodule exited with code 128

'''

What might be the issue. Please assist.

**Comment by Equious** [comment]
An unexpected disconnect is most commonly caused by an unstable network connection, in my experience. Are you able to try an alternative one?

**Comment by llakterian** [comment]
Thank you.
I fortunately managed to succeed.
