### ISSUE TITLE
Bug Report: `assertEq` Failing Test with "Invalid data" Error

### ISSUE THREAD

**Issue by Abhi270303** [Cyfrin/foundry-fund-me-f23#78]
# Bug Report: `assertEq` Failing Test with "Invalid data" Error

## The test fails with the following error:

\[

![Screenshot (139)](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/e3dfc991-4589-4835-a5f9-f90e7707ac43/604a91d2-0210-4aa4-9a8f-f075c72e0f07?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My9lM2RmYzk5MS00NTg5LTQ4MzUtYTVmOS1mOTBlNzcwN2FjNDMvNjA0YTkxZDItMDIxMC00YWE0LTlhOGYtZjA3NWM3MmUwZjA3IiwiaWF0IjoxNzE4MDIyMTczLCJleHAiOjMzMjg4NTgyMTczfQ.wv9MVwEB3TnnA7ddz4duSOHnVFQJs6P7-du8Zwa0Ad8)

\](url)

## My Code for this test is below:

```solidity
// SPDX-License-Identifier: SEE LICENSE IN LICENSE
pragma solidity ^0.8.18;
 
import {Test} from "forge-std/Test.sol";
 
contract FundMeTest is Test {
    uint256 number = 1;
 
    function setUp() external {
        number = 2;
    }
 
    function testDemo() public {
        emit log_uint(number);
        assertEq(number, 2);
    }
}
```

## Alternative which passes the test:

```solidity
function testDemo() external {
    emit log_uint(number); // This will log the value of 'number' to help with debugging
    require(number == 2, "Number is not equal to 2");
}
```

**Comment by Equious** [comment]
Try assigning your expected value to a typed variable before your assertion.

```js
function testDemo() public {
     uint256 expectedNumber = 2;
     emit log_uint(number);
     assertEq(number, expectedNumber);
    }
```

**Comment by Abhi270303** [comment]
Tried it! It Fails with the same reason "Invalid Data"!

**Comment by Equious** [comment]
Maybe try `forge clean` and `forge build` again.

This test just works for me locally:
![image](https://github.com/Cyfrin/foundry-fund-me-f23/assets/76449140/9d94bd35-ab13-43a9-a549-99e11321964c)
